user-signup:
  role: IamRestaurantAccountLambdaAccessRole
  handler: src/services/users/infrastructure/functions/http/signup/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsRestaurantAccountTopic
    MONGO_DATABASE_URI: ${ssm:/restaurant-account/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/restaurant-account/databases/MONGO_NAME}
    CRYPTO_SECRET_KEY: ${ssm:/restaurant-account/crypto/SECRET_KEY}
    CRYPTO_SECRET_IV: ${ssm:/restaurant-account/crypto/SECRET_IV}
    JWT_PRIVATE_KEY: ${ssm:/restaurant-account/jwt/PRIVATE_KEY}
  events:
    - httpApi:
        method: POST
        path: /account/users

user-notify-registered:
  role: IamRestaurantAccountLambdaAccessRole
  handler: src/services/users/infrastructure/functions/sns/notifRegistered/handler.handler
  environment:
    MONGO_DATABASE_URI: ${ssm:/restaurant-account/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/restaurant-account/databases/MONGO_NAME}
    SES_EMAIL_FROM: ${ssm:/restaurant-account/mailing/SES/SES_EMAIL_FROM}
  events:
    - sns:
        arn: !Ref EventBusSnsRestaurantAccountTopic
        topicName: ${self:custom.constants.RESTAURANT_ACCOUNT.SNS_TOPIC}
        filterPolicy:
          event_type:
            - 'soymichel-dev.account.v1.user.created'

user-get-all:
  role: IamRestaurantAccountLambdaAccessRole
  handler: src/services/users/infrastructure/functions/http/getAll/handler.handler
  environment:
    MONGO_DATABASE_URI: ${ssm:/restaurant-account/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/restaurant-account/databases/MONGO_NAME}
  events:
    - httpApi:
        method: GET
        path: /account/users

user-remove:
  role: IamRestaurantAccountLambdaAccessRole
  handler: src/services/users/infrastructure/functions/http/remove/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsRestaurantAccountTopic
    MONGO_DATABASE_URI: ${ssm:/restaurant-account/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/restaurant-account/databases/MONGO_NAME}
  events:
    - httpApi:
        method: DELETE
        path: /account/users/{userId}

user-notify-removed:
  role: IamRestaurantAccountLambdaAccessRole
  handler: src/services/users/infrastructure/functions/sns/notifRemoved/handler.handler
  environment:
    SES_EMAIL_FROM: ${ssm:/restaurant-account/mailing/SES/SES_EMAIL_FROM}
  events:
    - sns:
        arn: !Ref EventBusSnsRestaurantAccountTopic
        topicName: ${self:custom.constants.RESTAURANT_ACCOUNT.SNS_TOPIC}
        filterPolicy:
          event_type:
            - 'soymichel-dev.account.v1.user.removed'

user-signin:
  role: IamRestaurantAccountLambdaAccessRole
  handler: src/services/users/infrastructure/functions/http/signin/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsRestaurantAccountTopic
    MONGO_DATABASE_URI: ${ssm:/restaurant-account/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/restaurant-account/databases/MONGO_NAME}
    CRYPTO_SECRET_KEY: ${ssm:/restaurant-account/crypto/SECRET_KEY}
    CRYPTO_SECRET_IV: ${ssm:/restaurant-account/crypto/SECRET_IV}
    JWT_PRIVATE_KEY: ${ssm:/restaurant-account/jwt/PRIVATE_KEY}
  events:
    - httpApi:
        method: POST
        path: /account/users/signin
