order-history-create-sns:
  role: IamRestaurantKitchenLambdaAccessRole
  handler: src/services/ordersHistory/infrastructure/functions/sns/create/handler.handler
  maximumRetryAttempts: 0
  environment:
    MONGO_DATABASE_URI: ${ssm:/restaurant-kitchen/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/restaurant-kitchen/databases/MONGO_NAME}
  events:
    - sns:
        arn: !Ref EventBusSnsRestaurantKitchenTopic
        topicName: ${self:custom.constants.RESTAURANT_KITCHEN.SNS_TOPIC}
        filterPolicy:
          event_type:
            - 'soymichel-dev.restaurant-kitchen.v1.order.updated.state'
