Resources:
  EventBusSqsRestaurantKitchenQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      ReceiveMessageWaitTimeSeconds: 1
      DelaySeconds: 0
      VisibilityTimeout: 60
      FifoQueue: true
  EventBusSqsRestaurantKitchenQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref EventBusSqsRestaurantKitchenQueue
      PolicyDocument:
        Id: EventBusSqsRestaurantKitchenQueuePolicyId
        Version: '2012-10-17'
        Statement:
        - Sid: EventBusSqsRestaurantKitchenQueuePolicySidSelf
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::${self:custom.environment.AWS_ACCOUNT_ID}:root
          Action:
            - SQS:SendMessage
          Resource: !Ref EventBusSqsRestaurantKitchenQueue
