Resources:
  EventBusSnsRestaurantKitchenTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:custom.constants.RESTAURANT_KITCHEN.SNS_TOPIC}
  EventBusSnsRestaurantKitchenTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref EventBusSnsRestaurantKitchenTopic
      PolicyDocument:
        Id: EventBusSnsRestaurantKitchenTopicPolicyId
        Version: '2012-10-17'
        Statement:
        - Sid: EventBusSnsRestaurantKitchenTopicPolicySidSelf
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::${self:custom.environment.AWS_ACCOUNT_ID}:root
          Action:
            - SNS:GetTopicAttributes
            - SNS:SetTopicAttributes
            - SNS:AddPermission
            - SNS:RemovePermission
            - SNS:DeleteTopic
            - SNS:Subscribe
            - SNS:ListSubscriptionsByTopic
            - SNS:Publish
            - SNS:Receive
          Resource: !Ref EventBusSnsRestaurantKitchenTopic

Outputs:
  EventBusSnsRestaurantKitchenTopicArn:
    Value:
      Ref: EventBusSnsRestaurantKitchenTopic
    Export:
      Name: EventBusSnsRestaurantKitchenTopicArn
  EventBusSnsRestaurantKitchenTopicName:
    Value:  ${self:custom.constants.RESTAURANT_KITCHEN.SNS_TOPIC}
    Export:
      Name: EventBusSnsRestaurantKitchenTopicName
