Resources:
  IamRestaurantKitchenLambdaAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IamRestaurantKitchenLambdaAccessRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - ${self:custom.environment.RESTAURANT_WAREHOUSE.LAMBDA_ORDER_INGREDIENTS_STOCK}
              - Effect: Allow
                Action:
                  - SNS:Publish
                Resource:
                  Ref: EventBusSnsRestaurantKitchenTopic
              - Effect: 'Allow'
                Action:
                  - ssm:GetParameters
                Resource:
                - arn:aws:ssm:${self:custom.constants.REGION}:${self:custom.environment.AWS_ACCOUNT_ID}:parameter/deployment/restaurant-kitchen/*
              - Effect: 'Allow'
                Action:
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - Fn::Join:
                      - ''
                      - - Fn::GetAtt: [S3RestaurantKitchenStorage, Arn]
                        - '/*'
              - Effect: 'Allow'
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource:
                  - Fn::GetAtt: [EventBusSqsRestaurantKitchenQueue, Arn]
