Resources:
  S3RestaurantKitchenStorage:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3600

Outputs:
  S3RestaurantKitchenStorageName:
    Value:
      Ref: S3RestaurantKitchenStorage
    Export:
      Name: S3RestaurantKitchenStorageName
  S3RestaurantKitchenStorageArn:
    Value:
      Fn::GetAtt: [S3RestaurantKitchenStorage, Arn]
    Export:
      Name: S3RestaurantKitchenStorageArn