recipe-get-all:
  role: IamRestaurantKitchenLambdaAccessRole
  handler: src/services/recipes/infrastructure/functions/http/getAll/handler.handler
  environment:
    MONGO_DATABASE_URI: ${ssm:/restaurant-kitchen/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/restaurant-kitchen/databases/MONGO_NAME}
  events:
    - httpApi:
        method: GET
        path: /kitchen/recipes
