Resources:
  WarehouseDeploymentPolicies:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Políticas y permisos, del servicio Warehouse, necesarios para los sistemas de CI / CD
      Groups:
        - ${cf:restaurant-core-${self:provider.stage}.CIIAMGroupName}
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
              - iam:*
              - apigateway:*
              - cloudwatch:*
              - logs:*
              - lambda:*
              - events:*
              - sns:*
              - sqs:*
              - ssm:*
              - kms:*
            Resource: '*'
